name: Pull Request
on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  commitlint:
    name: Check CommitLint Compliance
    runs-on: ubuntu-latest
    steps:
      - name: GitHub Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: CommitLint
        uses: wagoid/commitlint-github-action@v3
        with:
          configFile: .commitlintrc.yml
  editorconfig:
    name: Check EditorConfig Compliance
    runs-on: ubuntu-latest
    steps:
      - name: GitHub Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: ECLint
        uses: snow-actions/eclint@v1.0.1
        with:
          args: 'check'

